### PR TITLE
Closes #42 and Closes #47: Adds integration tests (not complete) and support…

### LINKED ISSUE #42: RFC - Securing Actor-to-Actor Communications
# Current State
Actor to actor calls have been supported for quite some time, even though it wasn't really all that well advertised. Today, if you want an actor to be able to call another actor, then you need to add the _callee_ actor's public key to the list of capabilities for which the _calling_ actor is granted access. This means ensuring that your actor signing process knows ahead of time the public key of the actor that needs to be invoked.

# What Needs to Change and Why
As more developers start using waSCC in _lattice_ mode, there's a much higher chance that developers will want to take advantage of actor-to-actor calling. The current security system around actor-to-actor calling is somewhat of a hack in that you have to pretend that the public key of an actor is a capability ID when signing the actor.

This can be a source of friction. For example:
* What if your development environment uses different signing keys than your production environment? This means that the signing script for the actor will be different in development than it is in production because when you change a signing key, you also change the public key.
* What if you have a very large number of actors? Managing the allow-list of actors that can be invoked might be a huge source of friction and worse, _boilerplate_.
* What if you have a group of actors you want to be able to communicate amongst themselves, but all other actors you want to be unable to invoke other actors

# Solution
This is where I'd like feedback. There are a number of possibilities here. We could further extend the wascap claims to include an actor-specific allow list (thereby removing the "hacky" smell from treating an actor's public key like a capid). We could perform some kind of OAuth access token flow where an actor must ask "the lattice" for an auth token in order to be able to call another actor, which would then allow the token dispenser to be some kind of pluggable code. 

We could also defer the authorization decision of "can actor A call actor B" to Open Policy Agent. Further, we could combine the OAuth access token dispenser with an OPA  decision to determine if the communication is allowed, etc.

The main solution requirement is that it **must not** introduce further friction, boilerplate, or annoying process steps into the developer workflow, and that it **must** be suitable for enterprise-grade security to prevent unauthorized communication.

### LINKED ISSUE #47: Set up integration / acceptance tests
A number of the tests in the `examples` directory are really more like integration tests that I run locally to ensure that there's been no regressions when adding new features. We should add a number of key scenarios and execute them in the `/tests` directory (so they're separate crates from the one under test) using the `.assets` directory when we need capabilities and wasm modules to instantiate `WasccHost` instances.

Some of the initial key ones that I think we need (there are plenty more than this):

* Add/remove actor(s)
* Add/remove capability providers
* Multiple named bindings for the same provider
* Lattice running inproc (default bus)
* Lattice running against a loopback-bound NATS server (distributed bus)
* hot swap running actor (live update)
* Swap capability provider at runtime (this is likely to break given the details discussed in #46 )
* Middleware (halting and non-halting, pre, post, and around)
* Portable Capability Provider (wasm/wasi module acting as provider)
* ...

### PR DESCRIPTION
**Pull request by autodidaddict**
… for the new authorization trait

### CODE REVIEW

**Comment by autodidaddict** [comment]
By "not complete" on the integration tests, I mean that there are more that need to be written, but they aren't part of this PR. The tests for this PR to test the new authorizer trait _are_ complete.

**Comment by autodidaddict** [comment]
Removed a whole class of potentially difficult to troubleshoot and worse, security holes, by forcing the choice of authorizer at the instantiation time of the wascc host. You can't change the authorizer once you've created the host, so you can no longer have edge scenarios where one set of security rules applied to some lines of code but not others.

File: src/lib.rs [hunk 1]
```diff
@@ -556,12 +573,14 @@ impl WasccHost {
         authz::get_all_claims(self.claims.clone())
     }
 
-    /// Returns the list of capability providers registered in the host
+    /// Returns the list of capability providers registered in the host. The key is a tuple of (binding, capability ID)
     pub fn capabilities(&self) -> HashMap<(String, String), CapabilityDescriptor> {
```
Comment (brooksmtownsend) [inline src/lib.rs:590]: Random Rust thought here, would be neat to support named tuples so code helpers could tell you what each string is supposed to be

Comment (brooksmtownsend) [reply src/lib.rs:590]: To clarify, it would be neat if _Rust_ supported named tuples ;)

File: src/authz.rs [hunk 2]
```diff
@@ -13,15 +13,53 @@
...
+
+    // This doesn't actually mean everyone can invoke everything. Remember that the host itself
+    // will _always_ enforce the claims check on an actor having the required capability
+    // attestation
+    fn can_invoke(&self, _claims: &Claims<Actor>, target: &WasccEntity, _operation: &str) -> bool {
+        match target {
+            WasccEntity::Actor(_a) => true,
+            WasccEntity::Capability { .. } => true,
+        }
+    }
```
Comment (brooksmtownsend) [inline src/authz.rs:61]: Will this function always return `true`, or is it just placeholder return values for now that will be replaced with calls to the `can_invoke` function below once claims enforce per-operation calls?

File: tests/integration_core.rs [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+    std::thread::sleep(::std::time::Duration::from_millis(100));
+
+    let resp = reqwest::blocking::get("http://localhost:8081")?;
+    assert!(resp.status().is_success());
+    assert_eq!(resp.text()?,
+        "{\"method\":\"GET\",\"path\":\"/\",\"query_string\":\"\",\"headers\":{\"accept\":\"*/*\",\"host\":\"localhost:8081\"},\"body\":[]}"
+    );
+    host.shutdown()?;
+    std::thread::sleep(::std::time::Duration::from_millis(100));
```
Comment (brooksmtownsend) [inline tests/integration_core.rs]: Are these sleeps required here?

File: tests/integration_core.rs [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+    let mut con = client.get_connection()?;
+
+    let mut resp = reqwest::blocking::get(&url)?;
+    assert!(resp.status().is_success());
+    reqwest::blocking::get(&url)?;
+    resp = reqwest::blocking::get(&url)?; // counter should be at 3 now
+    assert!(resp.status().is_success());
+    assert_eq!(resp.text()?, "{\"counter\":3}");
+    host.shutdown()?;
+    std::thread::sleep(::std::time::Duration::from_millis(100));
```
Comment (brooksmtownsend) [inline tests/integration_core.rs]: See above comment

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
Authz looks great, glad we're getting some integration tests in as well. A couple comments / questions

File: src/authz.rs (hunk 2 above)
Comment (autodidaddict) [reply src/authz.rs:61]: It always returns true. I just put the match in there for clarity.

File: tests/integration_core.rs (hunk 3 above)
Comment (autodidaddict) [reply tests/integration_core.rs]: No, the sleeps after shutdown are not necessary. I originally had them because my tests were sharing the same HTTP port, but it was far more easier and reliable to give each test its own HTTP port.

File: src/lib.rs (hunk 1 above)
Comment (autodidaddict) [reply src/lib.rs:590]: In Rust, a named tuple is a `struct` ;)

I've converted the tuple into a struct to make things explicit and easier to read.

File: src/authz.rs (hunk 2 above)
Comment (brooksmtownsend) [reply src/authz.rs:61]: Is this function necessary then? It makes sense to me if additional checks will be added here in the future, but not if this function will always just return true

Comment (autodidaddict) [reply src/authz.rs:61]: Every authorizer must implement this function. Like I said, the only reason why I'm explicitly doing the match is so readers will have some sense of what their own implementations might look like.

Comment (autodidaddict) [reply src/authz.rs:61]: `authz::can_invoke` gets called _first_, and if that _succeeds_, then `can_invoke` on the `Authorizer` is invoked to see if further constraining will happen.

Comment (brooksmtownsend) [reply src/authz.rs:61]: Gotcha, I think I misunderstood the purpose of this function then. All good

**Review by brooksmtownsend — APPROVED** [review]
